language: java
deploy:
  provider: heroku
  api_key: 939426db-1aca-4a6b-a33d-79c177b38040
    secure: ThK7s/TCHCTbsJc5wKG83tyfs+zTO5Nmei1QEQRT/60peidntTr+jVa3D3x6IvPY2LrNADOmBNNeFO4FacP0FV9aPs3sIBNgESd+yOgb0TISrr5quCfURkfygfYvaRYGjfP7BDtugdT4A3o73sggNWjrNoP0uPcWEOm1Q6T/HbIQZHqbNS+XqnfBRJprR04YFu6Y5JZJZimeNksU6jRQCsvGLTHcN46Cuhs2bW4NIbXAZbFoGkjp5utIKecl8Tp83JEkYvOPlJNrQr/cDEvlILTC7WGfFigDEeJbVP+NAfHDl5EuC5JQhxtORoBlXTg0m8okJ33HJtmOdbPIJrA4tegXos9GsUBWom0WOqd/Tja3xApFam6w6QmDEJXR43vlWBOmr3NQN/ktw0dsd/vRrrSQc34e4Oov14ukdxRaC4+CZGa2c7FpevP4SzcjK9vvQRlZmm6SAhgk1AdgLKcyzDQC/UUctWyHMPMW4YufhOZ6SD8VmqJUm9ChXITGaHa+MT52ZovOZ894AoTqYtn2x3wtwHp4KmDVcMoGbq1Whbjwh9wo4oxPyTSuHa7yv9x5PxbhU3KOiz25sqh87Pwd2jWK+XEKr/zUa7eyHH3QzeOtTxRIDXcPATkFi3sjpKNyDGHfaHI9Ua6wkMwAowP9s9Ad+7i4/mc+22RvBBiLYi0=
  app: stormy-hamlet-11885
  on:
    repo: maggaou/wepa2017-AliveApplication
