language: java
deploy:
  provider: heroku
  api_key:
    secure: 3z3P9j9JFU0Z/BJyOJHYJCkPIO9zp0krauJ53TcpUI6c5wQF1z+b5EvvvcBAe1+4CZcU3EQSBbKneL3Co/UrYGPpY0HnibP+JdaChzTVuYrzr+f8FLIF0IDh5xPuYnT3MqU0ja4YWTloRi/i027kStfZRkn3GCk4e2UX34PFn6CB7d0sscFwyWYl0PXh5iAtOzYiSpO+uO0qSsIyzdWwXLubXexwGoABNNyZqOjuMiXgX+CFUUVTC1h+aFYV0qWyu+rzyLs5OyKpGr07Gln8bs95Ht/pbYw/oiGPnPkvXKud8mJePOtaL4HhjIIkC5uGveCyIUztUT/RZk147eaxDJ7phb9GJ2GZvn/RVng40Yo6qJm/36qepF9cqvpX12wo8X1SEA3+We9QUEbtoKlZrd/cKZiFL/+x3prJ7b1KfaCucm4ALjqwpuyHQHiHw5Opu3xgaLGcLUXe5MeW0lKiqRN0ZtsEPwPvEYD/ypOCt6y0ehw4/lKdJHTFCVWV48xo5vfoG9Y+HmPLqCIq+B3dw3Oj/FIhTd38HPdjIJNGGRF+PlYUva3NJNmXvmMfg/nzosc3PYTbMpDVzOCVdb17GLo2UQvARPDsi0P/DUgBAZEsooV4NCP4GHkKAfaaeoKugjkFhU2q3wvAOVZ2GoqGC1Q2gwEka8cxS5lhkO45YTs=
  app: stormy-hamlet-11885
  on:
    repo: maggaou/wepa2017-AliveApplication
